# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7e9f529f0b86c514fa8e5464458ab92"
application_url = "https://answering-treasury-lease-spend.trycloudflare.com"
embedded = true
name = "app-chatbot"
handle = "base-app-43"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://answering-treasury-lease-spend.trycloudflare.com/auth/callback",
  "https://answering-treasury-lease-spend.trycloudflare.com/auth/shopify/callback",
  "https://answering-treasury-lease-spend.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://answering-treasury-lease-spend.trycloudflare.com"
subpath = "chatbot"
prefix = "apps"

[pos]
embedded = false
